<?php

namespace AppBundle\Repository;

/**
 * InspectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspectorRepository extends \Doctrine\ORM\EntityRepository
{
}
