<?php

namespace AppBundle\Repository;

/**
 * MilestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilestoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrdered($projectId){
        return $this->createQueryBuilder('cat')
                     ->andWhere('cat.projectId = :searchTerm')
                     ->setParameter('searchTerm',$projectId)
                     ->getQuery()
                     ->execute();
    }
    public function findId($id){
        return $this->createQueryBuilder('cat')
                    ->andWhere("cat.id = :searchTerm")
                    ->setParameter('searchTerm',$id)
                    ->getQuery()
                    ->execute();
    }
    public function findAllOrdered(){
        return $this->createQueryBuilder('cat')
                  ->getQuery()
                  ->execute();
    }
}
