<?php

namespace AppBundle\Repository;

/**
 * ProjectMemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectMemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMe($projectId){
        return $this->createQueryBuilder('cat')
                    ->andWhere('cat.projectId= :searchTerm')
                    ->setParameter('searchTerm',$projectId)
                    ->getQuery()
                    ->execute();
    }
    public function findId($id){
        return $this->createQueryBuilder('cat')
                    ->andWhere("cat.projectId = :searchTerm")
                    ->setParameter('searchTerm',$id)
                    ->getQuery()
                    ->execute();
    }
}
