<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
      public function findAllOrdered(){
        return $this->createQueryBuilder('cat')
                  ->getQuery()
                  ->execute();
    }
     public function findId($id){
        return $this->createQueryBuilder('cat')
                    ->andWhere("cat.id = :searchTerm")
                    ->setParameter('searchTerm',$id)
                    ->getQuery()
                    ->execute();
    }
}
