<?php

namespace AppBundle\Repository;

/**
 * TaskMemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskMemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findId($id){
        return $this->createQueryBuilder('cat')
                    ->andWhere("cat.taskId = :searchTerm")
                    ->setParameter('searchTerm',$id)
                    ->getQuery()
                    ->execute();
    }
}
