<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMe($milestoneId){
        return $this->createQueryBuilder('cat')
                    ->andWhere('cat.milestoneId= :searchTerm')
                    ->setParameter('searchTerm',$milestoneId)
                    ->getQuery()
                    ->execute();
    }

    public function findId($id){
        return $this->createQueryBuilder('cat')
                    ->andWhere("cat.id = :searchTerm")
                    ->setParameter('searchTerm',$id)
                    ->getQuery()
                    ->execute();
    }

    public function findDes($taskId){
        return $this->createQueryBuilder('cat')
                    ->andWhere('cat.id= :searchTerm')
                    ->setParameter('searchTerm',$taskId)
                    ->getQuery()
                    ->execute();
    }
    public function findAllOrdered(){
        return $this->createQueryBuilder('cat')
                  ->getQuery()
                  ->execute();
    }
}
